version: '3.9'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - pgsql

  pgsql:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
